import "./About.css";

export default function About() {
  return (
    <section className="about-section">
      <div className="about-hero">
        <h1>About Rick & Morty Lab</h1>
        <p className="hero-subtitle">
          Explore the multiverse through an interactive web application
        </p>
      </div>

      <div className="about-content">
        <div className="feature-grid">
          <div className="feature-card">
            <div className="feature-icon">🚀</div>
            <h3>Characters Explorer</h3>
            <p>
              Browse and search through 800+ characters from the Rick and Morty
              universe with detailed information about each one.
            </p>
          </div>

          <div className="feature-card">
            <div className="feature-icon">🌍</div>
            <h3>Locations Database</h3>
            <p>
              Discover 126 unique locations across different dimensions and
              realities in the Rick and Morty multiverse.
            </p>
          </div>

          <div className="feature-card">
            <div className="feature-icon">📺</div>
            <h3>Episodes Guide</h3>
            <p>
              Complete episode guide with 61 episodes featuring character
              appearances and air dates.
            </p>
          </div>

          <div className="feature-card">
            <div className="feature-icon">🤖</div>
            <h3>AI-Generated Quotes</h3>
            <p>
              Experience Rick and Morty style quotes generated by Cohere AI on
              the home page.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
